version: 2.1

jobs:
  run-tests:
    working_directory: ~/AlgoLib_Python
    docker:
      - image: cimg/python:3.9
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: requirements
          command: pip install -r requirements.txt
      - run:
          name: tests
          command: nose2 tests

workflows:
  main:
    jobs:
      - run-tests
