version: 2.1

jobs:
  run-tests:
    parameters:
      python-version:
        type: string
        default: latest
    working_directory: ~/AlgoLib_Python
    docker:
      - image: cimg/python:<< parameters.python-version >>
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: requirements
          command: pip install -r requirements.txt
      - run:
          name: tests
          command: nose2 tests

workflows:
  main:
    jobs:
      - run-tests:
          python-version: "3.11"
      - run-tests:
          python-version: "3.10"
      - run-tests:
          python-version: "3.9"
