version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  run-tests:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Test
          command: nose2 tests

workflows:
  main:
    jobs:
      - run-tests
